### ISSUE TITLE
Enable GitHub pages

### ISSUE THREAD

**Issue by bkmgit** [IETF-Hackathon/ietf116-project-presentations#1]
@bjovereinder Can you enable GitHub pages so that https://ietf-hackathon.github.io/ietf116-project-presentations/hackathon-presentation-template.html becomes visible? See https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site then enable the main branch as the source.

**Comment by bjovereinder** [comment]
Thanks for pointing this out.  Enabled the main brach and should work now.  Just tested myself.

**Comment by bkmgit** [comment]
Thanks for the quick update.
